# Generated by Django 3.1.5 on 2021-04-11 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizapp', '0002_auto_20210411_1716'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='created',
        ),
    ]
